# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc9807653df1c3f377dd0b8c5773e01b52f94ed8be4fe9469921e64b9085c98b85939b7bc41948a4293fad7c6f9765234ee4fceb9e5e73372bb03a5acb5bdd2

test:
  secret_key_base: 89370d522c250d791e1b0cc3a6f9e6c7df135850f1a5d1d89b5f76e3c5e2bcc4e26c1a9689140359de98bd0bef6f5c642e7be9c46a65a4c82d02f8ef8fbb8b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
